config/routes.rb
Tirashinoura::Application.routes.draw do
  resources :diaries do
    resources :comments, only: [:new, :create]
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :diary
end

app/models/diary.rb
class Diary < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    diary = Diary.find params[:diary_id]
    binding.pry
    diary.comments.create comment_params
    redirect_to diaries_path
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @diary }
      else
        format.html { render action: 'new' }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/comments/_comment.html.erb
<%= form_for [comment.diary, comment] do |f| %>
<%= f.label :comment , 'any comment?' %>
<%= f.text_area :comment %>
<%= f.submit %>
<% end %>

app/views/diaries/_form.html.erb
<%= form_for(@diary) do |f| %>
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% @diary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing diary</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<h1>ちらしのうら</h1>

<table>
  <thead>
    <tr>
      <th>たいとる</th>
      <th>ほんぶん</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.title %></td>
        <td><%= diary.content %></td>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>

app/views/diaries/new.html.erb
<h1>New diary</h1>

<%= render 'form' %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @diary.content %>
</p>

<p>
  <strong>Comment:</strong>
</p>
</p >
  <% @diary.comments.each do |comment| %>
    <%= comment.comment %> |
    <%= comment.created_at %>
    <br />
  <% end %>
</p>

<%= render @diary.comments.build %>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tirashinoura</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>